import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import type { Page } from '@playwright/test'
async function openView(page:Page,name:string) {
 const labels:Record<string,string>={'Votre contexte':'Recommander','Les suggestions':'Familles','Comparer A/B':'Comparer','Vérifier':'Créer un bouton','Références':'Référentiels'}
 await page.getByRole('tab',{name:labels[name] ?? name,exact:true}).click()
}
async function selectPair(page:Page) {
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true}).click()
 await page.getByRole('button',{name:'Ajouter Carré à la comparaison',exact:true}).click()
}
test('recommandation, sources, sélection A/B et favoris persistants',async({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Recommander une forme'})).toBeVisible()
  await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
  await page.getByRole('radio',{name:'Rigoureux'}).click()
  await page.getByLabel('Public',{exact:true}).selectOption('expert')
  await page.getByRole('button',{name:'Recommander une forme'}).click()
  await expect(page.getByRole('tab',{name:'Recommander',exact:true})).toHaveAttribute('data-state','active')
  await expect(page.locator('.recommendation-result .family-card')).toHaveCount(1)
  await expect(page.locator('.recommendation-result .family-card h3')).toHaveText('Carré')
  await expect(page.getByRole('heading',{name:'La forme recommandée'})).toBeFocused()
  const explanation=page.locator('.family-card').first().getByRole('button',{name:'Pourquoi cette forme : Carré ?'})
  await explanation.click()
  await expect(page.getByRole('dialog')).toHaveAccessibleName('Carré : pourquoi cette forme ?')
  await expect(page.getByRole('dialog').locator('.source-links a')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(explanation).toBeFocused()
  await page.getByRole('button',{name:'Ajouter Carré à la comparaison',exact:true}).click()
  await page.getByRole('button',{name:'Ajouter Carré aux favoris',exact:true}).click()
  await openView(page,'Familles')
  await expect(page.locator('.all-families .family-card')).toHaveCount(6)
  await expect(page.locator('.all-families .match-reason,.all-families .recommendation-badge')).toHaveCount(0)
  await openView(page,'Favoris')
  await expect(page.locator('.family-card')).toHaveCount(1)
  await page.reload()
  await openView(page,'Favoris')
  await expect(page.locator('.family-card h3')).toHaveText('Carré')
  expect(errors).toEqual([])
})
test('comparaison, correction de cohérence et accessibilité',async({page})=>{
  await page.goto('/')
  await selectPair(page)
  await openView(page,'Comparer A/B')
  await expect(page.locator('.system-preview')).toHaveCount(2)
  await page.locator('.advanced-settings summary').first().click()
  await page.getByRole('slider',{name:'Rayon intérieur A',exact:true}).fill('20')
  await expect(page.getByText('Imbrication à ajuster')).toBeVisible()
  await page.getByRole('button',{name:'Aligner le rayon intérieur sur 8 px'}).click()
  await expect(page.getByRole('slider',{name:'Rayon intérieur A',exact:true})).toHaveValue('8')
  await page.getByRole('slider',{name:'Hauteur des cibles A',exact:true}).fill('20')
  await page.locator('#A-bg').fill('#ffffff')
  await page.getByRole('button',{name:'Créer mon bouton'}).click()
  const a=page.locator('.workshop-checks')
  await expect(a.locator('.audit-row').filter({hasText:'Contraste du texte'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
  await expect(a.locator('.audit-row').filter({hasText:'Cible minimale'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
})
test('export, import et rejet de JSON invalide',async({page})=>{
  await page.goto('/')
  await expect(page.getByLabel('Nom de l’exploration')).toHaveCount(0)
  await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
  await page.locator('.file-menu summary').click()
  const downloaded=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exporter',exact:true}).click()
  const file=await downloaded
  expect(file.suggestedFilename()).toBe('forme-exploration.json')
  const path=await file.path()
  await page.getByLabel('Secteur',{exact:true}).selectOption('culture')
  await page.getByLabel('Importer une exploration JSON').setInputFiles(path!)
  await expect(page.getByLabel('Secteur',{exact:true})).toHaveValue('finance')
  await page.getByLabel('Importer une exploration JSON').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":2}')})
  await expect(page.getByRole('status')).toContainText('Projet invalide')
  await expect(page.getByLabel('Secteur',{exact:true})).toHaveValue('finance')
})
test('navigation clavier et contrôles automatiques d’accessibilité',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  const tabs=page.getByRole('tab',{name:'Familles',exact:true})
  await tabs.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Comparer',exact:true})).toBeFocused()
  await expect(page.getByText('Choisissez deux familles',{exact:true})).toBeVisible()
  await selectPair(page)
  for(const tab of ['Votre contexte','Les suggestions','Comparer A/B','Vérifier','Favoris','Références']) {
    await openView(page,tab)
    const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
    expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
  }
})
for(const width of [375,768,1024,1440]) {
  test(`aucun débordement à ${width}px`,async({page})=>{
    await page.setViewportSize({width,height:1000})
    await page.goto('/')
    for(const tab of ['Votre contexte','Les suggestions','Comparer A/B','Vérifier','Favoris','Références']) {
      await openView(page,tab)
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
    }
  })
}

test('parcours guidé jusqu’au choix et références RGAA',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Recommander une forme'}).click()
  await selectPair(page)
  await page.getByRole('button',{name:'Passer à la comparaison'}).click()
  await expect(page.getByRole('button',{name:'Créer mon bouton'})).toBeEnabled()
  await expect(page.getByRole('slider',{name:'Rayon intérieur A',exact:true})).toBeHidden()
  await page.getByRole('button',{name:'Retenir l’option A'}).click()
  await page.getByRole('button',{name:'Créer mon bouton'}).click()
  await expect(page.getByText('RGAA 4.1.2',{exact:true})).toBeVisible()
  await expect(page.getByLabel('Forme de départ')).toHaveValue('soft')
  await expect(page.locator('.workshop-checks')).toContainText('RGAA 3.2')
  await expect(page.locator('.workshop-checks')).toContainText('RGAA 3.3')
  await expect(page.locator('.draft-button')).toBeVisible()
})

test('boîte à outils sans fil d’Ariane et états colorés',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.breadcrumb')).toHaveCount(0)
 await expect(page.getByRole('tab')).toHaveCount(6)
 await openView(page,'Vérifier')
 await expect(page.locator('.audit-success .audit-status').first()).toHaveAccessibleName('Contrôle vérifié')
 await expect(page.locator('.audit-manual .audit-status').first()).toHaveAccessibleName('À évaluer manuellement')
 await openView(page,'Références')
 await expect(page.getByRole('heading',{name:'Accessibilité',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'RGAA 4.1.2 · Critères et tests',exact:true})).toBeVisible()
})

test('navigation élargie et repliable',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.sidebar-logo')).toHaveAttribute('alt','Forme')
 const toggle=page.getByRole('button',{name:'Réduire la barre latérale'})
 await expect(toggle).toHaveAttribute('aria-expanded','true')
 await expect(page.locator('.rail-label').first()).toBeVisible()
 await toggle.click()
 await expect(page.getByRole('button',{name:'Développer la barre latérale'})).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('.tool-layout')).toHaveClass(/sidebar-collapsed/)
 await page.getByRole('button',{name:'Développer la barre latérale'}).click()
 await expect(page.locator('.tool-layout')).not.toHaveClass(/sidebar-collapsed/)
})
test('export PDF avec une synthèse imprimable',async({page})=>{
 await page.goto('/')
 await selectPair(page)
 await page.evaluate(()=>{(window as typeof window & {printCalls:number}).printCalls=0;window.print=()=>{(window as typeof window & {printCalls:number}).printCalls++}})
 await page.locator('.file-menu summary').click()
 await page.getByRole('button',{name:'Exporter en PDF',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>(window as typeof window & {printCalls:number}).printCalls)).toBe(1)
 await page.emulateMedia({media:'print'})
 await expect(page.locator('.tool-layout')).toBeHidden()
 await expect(page.locator('.print-report')).toBeVisible()
 await expect(page.locator('.report-system')).toHaveCount(2)
 const pdf=await page.pdf({format:'A4',printBackground:true})
 expect(pdf.subarray(0,5).toString()).toBe('%PDF-')
 expect(pdf.length).toBeGreaterThan(10000)
})

test('ajout, limite et retrait de la comparaison avec compteur persistant',async({page})=>{
 await page.goto('/')
 await selectPair(page)
 await expect(page.locator('.comparison-count')).toHaveText('2')
 await page.getByRole('button',{name:'Ajouter Pilule à la comparaison',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('déjà deux familles')
 await expect(page.locator('.comparison-count')).toHaveText('2')
 await page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await openView(page,'Comparer')
 await expect(page.locator('.system-panel')).toHaveCount(1)
 await expect(page.getByLabel('Famille du système A')).toHaveValue('square')
 await page.reload()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await openView(page,'Comparer')
 await page.getByRole('button',{name:'Retirer Carré de la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveCount(0)
 await expect(page.getByText('Choisissez deux familles',{exact:true})).toBeVisible()
})

test('sélection visible, popup accessible et aperçu de réservation',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Familles')
 const add=page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true})
 await expect(add).toHaveCSS('background-color','rgb(255, 255, 255)')
 await add.click()
 const selected=page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true})
 await expect(selected).toHaveAttribute('aria-pressed','true')
 await page.mouse.move(0,0)
 await expect(selected).toHaveCSS('background-color','rgb(24, 24, 27)')
 await page.getByRole('button',{name:'Pourquoi cette forme : Arrondi léger ?'}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.getByText('Points d’attention',{exact:true})).toBeVisible()
 const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(accessibility.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
 await dialog.getByRole('button',{name:'Fermer',exact:true}).click()
 await openView(page,'Comparer')
 await expect(page.getByRole('heading',{name:'Réserver un atelier',exact:true})).toBeVisible()
 const remove=page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true})
 await remove.hover()
 // Wait for the button's colour transition to settle before inspecting the hover.
 await expect(remove).toHaveCSS('color','rgb(185, 28, 28)')
 const background=await remove.evaluate(button=>getComputedStyle(button).backgroundColor)
 expect(background).toMatch(/0\.05|5%/)
 await page.getByLabel('Votre adresse e-mail',{exact:true}).fill('test@example.com')
 await page.getByRole('button',{name:'Réserver ma place dans le système A',exact:true}).click()
 await expect(page.getByText('Exemple uniquement : aucune réservation n’est envoyée.')).toBeVisible()
 await page.setViewportSize({width:375,height:800})
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Pourquoi cette forme : Arrondi léger ?'}).click()
 const bounds=await page.getByRole('dialog').boundingBox()
 expect(bounds!.x).toBeGreaterThanOrEqual(0)
 expect(bounds!.width).toBeLessThanOrEqual(375)
 expect(bounds!.height).toBeLessThanOrEqual(800)
 await expect(page.getByRole('dialog').getByRole('button',{name:'Fermer',exact:true})).toBeInViewport()
})


test('recommandation sur place et catalogue indépendant du contexte',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await page.getByRole('button',{name:'Recommander une forme'}).click()
 await expect(page.locator('.recommendation-result h3')).toHaveText('Arrondi léger')
 await page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await page.getByRole('button',{name:'Voir la comparaison',exact:true}).click()
 await expect(page.locator('.system-panel')).toHaveCount(1)
 await openView(page,'Familles')
 const names=await page.locator('.all-families h3').allTextContents()
 await expect(page.locator('.all-families .match-reason,.all-families .recommendation-badge')).toHaveCount(0)
 await openView(page,'Recommander')
 await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
 await page.getByRole('radio',{name:'Rigoureux'}).click()
 await page.getByLabel('Public',{exact:true}).selectOption('expert')
 await expect(page.locator('.recommendation-result h3')).toHaveText('Carré')
 const a11y=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(a11y.violations.map(v=>v.id)).toEqual([])
 await openView(page,'Familles')
 expect(await page.locator('.all-families h3').allTextContents()).toEqual(names)
 await page.setViewportSize({width:375,height:900})
 await openView(page,'Recommander')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await expect(page.locator('.recommendation-result h3')).toHaveText('Carré')
})


test('création du bouton, mesures réelles, contrôles et sauvegarde',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Vérifier')
 const preview=page.locator('.draft-button')
 const check=(title:string)=>page.locator('.workshop-checks .audit-row').filter({hasText:title})
 await expect(check('Cible renforcée').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 const before=await preview.boundingBox()
 await page.getByRole('slider',{name:'Padding horizontal'}).fill('40')
 await expect.poll(async()=> (await preview.boundingBox())!.width).toBeGreaterThan(before!.width+35)
 await page.getByRole('slider',{name:'Padding vertical'}).fill('0')
 await expect(check('Cible minimale').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('slider',{name:'Padding vertical'}).fill('16')
 await expect(check('Cible renforcée').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 await page.getByLabel('Fond du bouton',{exact:true}).fill('#777777')
 await expect(check('Contraste du texte').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('slider',{name:'Taille du texte'}).fill('24')
 await expect(check('Contraste du texte').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 await page.getByLabel('Texte du bouton').fill('Réserver ma place')
 const rect=await preview.boundingBox()
 await expect(page.locator('.workshop-dimensions')).toHaveText(`${rect!.width.toFixed(1)} × ${rect!.height.toFixed(1)} px`)
 await preview.focus()
 await page.keyboard.press('Enter')
 await expect(page.locator('.workshop-interaction')).toContainText('Bouton activé')
 await page.reload()
 await openView(page,'Vérifier')
 await expect(page.getByLabel('Texte du bouton')).toHaveValue('Réserver ma place')
 await expect(page.getByRole('slider',{name:'Padding horizontal'})).toHaveValue('40')
 await page.getByLabel('Texte du bouton').fill('')
 await expect(check('Présence du libellé').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Réinitialiser le bouton'}).click()
 await expect(page.getByLabel('Texte du bouton')).toHaveValue('Continuer')
 await page.setViewportSize({width:375,height:900})
 await page.getByLabel('Texte du bouton').fill('Un libellé volontairement très long pour vérifier le retour à la ligne sur un petit écran')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 const resized=await preview.boundingBox()
 await expect(page.locator('.workshop-dimensions')).toHaveText(`${resized!.width.toFixed(1)} × ${resized!.height.toFixed(1)} px`)
})


test('sliders compacts, valeurs manuelles et liens au survol',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Vérifier')
 await expect(page.locator('.workshop-parameters .parameter-slider')).toHaveCount(6)
 const value=page.getByRole('textbox',{name:'Valeur : Padding horizontal',exact:true})
 await value.click()
 await value.fill('32')
 await value.press('Enter')
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await expect(page.locator('.draft-button')).toHaveCSS('padding-left','32px')
 await value.click()
 await value.fill('50')
 await value.press('Escape')
 await expect(value).toHaveValue('32')
 const size=page.getByRole('textbox',{name:'Valeur : Taille du texte',exact:true})
 await size.fill('999')
 await size.press('Enter')
 await expect(size).toHaveValue('48')
 await size.fill('')
 await size.press('Tab')
 await expect(size).toHaveValue('48')
 await openView(page,'Familles')
 const explanation=page.getByRole('button',{name:'Pourquoi cette forme : Carré ?'})
 await explanation.hover()
 await expect(explanation).toHaveCSS('color','rgb(0, 0, 0)')
 await expect(explanation).toHaveCSS('text-decoration-line','underline')
 await explanation.click()
 const reference=page.getByRole('dialog').locator('.source-links a').first()
 await reference.hover()
 await expect(reference).toHaveCSS('color','rgb(0, 0, 0)')
})


test('usage de recommandation, bibliothèque de styles et ressources Orange',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await page.getByLabel('Secteur',{exact:true}).selectOption('culture')
 await page.getByLabel('Public',{exact:true}).selectOption('jeune')
 await page.getByRole('radio',{name:'Expressif'}).click()
 await page.getByLabel('Usage prévu').selectOption('identity')
 await page.getByRole('button',{name:'Recommander une forme'}).click()
 await expect(page.locator('.recommendation-result h3')).toHaveText('Triangle')
 await page.getByLabel('Usage prévu').selectOption('button')
 await expect(page.locator('.recommendation-result h3')).toHaveText('Pilule')
 await expect(page.locator('.recommendation-reasons')).toContainText('action avec du texte')
 await openView(page,'Vérifier')
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('32')
 await page.getByRole('button',{name:'Enregistrer le bouton dans les favoris',exact:true}).click()
 await page.getByLabel('Nom du bouton').fill('Action principale')
 await page.getByRole('dialog').getByRole('button',{name:'Enregistrer le bouton',exact:true}).click()
 await expect(page.getByLabel('Styles enregistrés')).toHaveCount(0)
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('5')
 await openView(page,'Favoris')
 await page.getByRole('button',{name:'Modifier le bouton Action principale',exact:true}).click()
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await page.reload()
 await openView(page,'Vérifier')
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('4')
 await openView(page,'Favoris')
 await page.getByRole('button',{name:'Modifier le bouton Action principale',exact:true}).click()
 await expect(page.locator('.draft-button')).toHaveCSS('padding-left','32px')
 await page.locator('.file-menu summary').click()
 const download=page.waitForEvent('download')
 await page.getByRole('button',{name:'Exporter',exact:true}).click()
 const file=await download
 const path=await file.path()
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('3')
 await page.getByLabel('Importer une exploration JSON').setInputFiles(path!)
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Pourquoi cette forme : Carré ?'}).click()
 await expect(page.getByRole('dialog').getByText('Émotions et associations',{exact:true})).toBeVisible()
 await expect(page.getByRole('dialog').locator('.shape-associations')).toContainText('Rigueur')
 await page.keyboard.press('Escape')
 await openView(page,'Références')
 const orange=page.locator('.source-card').filter({hasText:'Orange · Recommandations'})
 await expect(orange.getByRole('img',{name:'Orange',exact:true})).toBeVisible()
 await expect(orange.getByRole('link',{name:'Consulter'})).toHaveAttribute('href','https://a11y-guidelines.orange.com/fr/')
})
