import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import type { Page } from '@playwright/test'
async function openView(page:Page,name:string) {
 const labels:Record<string,string>={'Votre contexte':'Recommander','Les suggestions':'Familles','Comparer A/B':'Comparer','Vérifier':'Créer un bouton','Références':'Référentiels'}
 await page.getByRole('tab',{name:labels[name] ?? name,exact:true}).click()
}
async function selectPair(page:Page) {
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true}).click()
 await page.getByRole('button',{name:'Ajouter Carré à la comparaison',exact:true}).click()
}
test('recommandation, sources, sélection A/B et favoris persistants',async({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Recommander une forme'})).toBeVisible()
  await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
  await page.getByRole('radio',{name:'Rigoureux'}).click()
  await page.getByLabel('Public',{exact:true}).selectOption('expert')
  await page.getByRole('button',{name:'Recommander une forme'}).click()
  await expect(page.getByRole('tab',{name:'Recommander',exact:true})).toHaveAttribute('data-state','active')
  await expect(page.locator('.recommendation-result .family-card')).toHaveCount(1)
  await expect(page.locator('.recommendation-result .family-card h3')).toHaveText('Carré')
  await expect(page.getByRole('heading',{name:'La forme recommandée'})).toBeFocused()
  const explanation=page.locator('.family-card').first().getByRole('button',{name:'Pourquoi cette forme : Carré ?'})
  await explanation.click()
  await expect(page.getByRole('dialog')).toHaveAccessibleName('Carré : pourquoi cette forme ?')
  await expect(page.getByRole('dialog').locator('.source-links a')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(explanation).toBeFocused()
  await page.getByRole('button',{name:'Ajouter Carré à la comparaison',exact:true}).click()
  await page.getByRole('button',{name:'Ajouter Carré aux favoris',exact:true}).click()
  await openView(page,'Familles')
  await expect(page.locator('.all-families .family-card')).toHaveCount(6)
  await expect(page.locator('.all-families .match-reason,.all-families .recommendation-badge')).toHaveCount(0)
  await openView(page,'Favoris')
  await expect(page.locator('.family-card')).toHaveCount(1)
  await page.reload()
  await openView(page,'Favoris')
  await expect(page.locator('.family-card h3')).toHaveText('Carré')
  expect(errors).toEqual([])
})
test('comparaison, correction de cohérence et accessibilité',async({page})=>{
  await page.goto('/')
  await selectPair(page)
  await openView(page,'Comparer A/B')
  await expect(page.locator('.system-preview')).toHaveCount(2)
  await page.locator('.advanced-settings summary').first().click()
  await page.getByRole('slider',{name:'Rayon intérieur A',exact:true}).fill('20')
  await expect(page.getByText('Imbrication à ajuster')).toBeVisible()
  await page.getByRole('button',{name:'Aligner le rayon intérieur sur 8 px'}).click()
  await expect(page.getByRole('slider',{name:'Rayon intérieur A',exact:true})).toHaveValue('8')
  await page.getByRole('slider',{name:'Hauteur des cibles A',exact:true}).fill('20')
  await page.locator('#A-bg').fill('#ffffff')
  await page.getByRole('button',{name:'Créer mon bouton'}).click()
  const a=page.locator('.workshop-checks')
  await expect(a.locator('.audit-row').filter({hasText:'Contraste du texte'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
  await expect(a.locator('.audit-row').filter({hasText:'Cible minimale'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
})
test('export, import et rejet de JSON invalide',async({page})=>{
  await page.goto('/')
  await expect(page.getByLabel('Nom de l’exploration')).toHaveCount(0)
  await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
  await page.locator('.file-menu summary').click()
  const downloaded=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exporter',exact:true}).click()
  const file=await downloaded
  expect(file.suggestedFilename()).toBe('forme-exploration.json')
  const path=await file.path()
  await page.getByLabel('Secteur',{exact:true}).selectOption('culture')
  await page.getByLabel('Importer une exploration JSON').setInputFiles(path!)
  await expect(page.getByLabel('Secteur',{exact:true})).toHaveValue('finance')
  await page.getByLabel('Importer une exploration JSON').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":2}')})
  await expect(page.getByRole('status')).toContainText('Projet invalide')
  await expect(page.getByLabel('Secteur',{exact:true})).toHaveValue('finance')
})
test('navigation clavier et contrôles automatiques d’accessibilité',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  const tabs=page.getByRole('tab',{name:'Familles',exact:true})
  await tabs.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Comparer',exact:true})).toBeFocused()
  await expect(page.getByText('Choisissez deux familles',{exact:true})).toBeVisible()
  await selectPair(page)
  for(const tab of ['Votre contexte','Les suggestions','Comparer A/B','Vérifier','Favoris','Références']) {
    await openView(page,tab)
    const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
    expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
  }
})
for(const width of [375,768,1024,1440]) {
  test(`aucun débordement à ${width}px`,async({page})=>{
    await page.setViewportSize({width,height:1000})
    await page.goto('/')
    for(const tab of ['Votre contexte','Les suggestions','Comparer A/B','Vérifier','Favoris','Références']) {
      await openView(page,tab)
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
    }
  })
}

test('parcours guidé jusqu’au choix et références RGAA',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Recommander une forme'}).click()
  await selectPair(page)
  await page.getByRole('button',{name:'Passer à la comparaison'}).click()
  await expect(page.getByRole('button',{name:'Créer mon bouton'})).toBeEnabled()
  await expect(page.getByRole('slider',{name:'Rayon intérieur A',exact:true})).toBeHidden()
  await page.getByRole('button',{name:'Retenir l’option A'}).click()
  await page.getByRole('button',{name:'Créer mon bouton'}).click()
  await expect(page.getByText('RGAA 4.1.2',{exact:true})).toBeVisible()
  await expect(page.getByLabel('Forme de départ')).toHaveValue('soft')
  await expect(page.locator('.workshop-checks')).toContainText('RGAA 3.2')
  await expect(page.locator('.workshop-checks')).toContainText('RGAA 3.3')
  await expect(page.locator('.draft-button')).toBeVisible()
})

test('boîte à outils sans fil d’Ariane et états colorés',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.breadcrumb')).toHaveCount(0)
 await expect(page.getByRole('tab')).toHaveCount(6)
 await openView(page,'Vérifier')
 await expect(page.locator('.audit-success .audit-status').first()).toHaveAccessibleName('Contrôle vérifié')
 await expect(page.locator('.audit-manual .audit-status').first()).toHaveAccessibleName('À évaluer manuellement')
 await openView(page,'Références')
 await expect(page.getByRole('heading',{name:'Accessibilité',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'RGAA 4.1.2 · Critères et tests',exact:true})).toBeVisible()
})

test('navigation élargie et repliable',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.sidebar-logo')).toHaveAttribute('alt','Forme')
 const toggle=page.getByRole('button',{name:'Réduire la barre latérale'})
 await expect(toggle).toHaveAttribute('aria-expanded','true')
 await expect(page.locator('.rail-label').first()).toBeVisible()
 await toggle.click()
 await expect(page.getByRole('button',{name:'Développer la barre latérale'})).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('.tool-layout')).toHaveClass(/sidebar-collapsed/)
 await page.getByRole('button',{name:'Développer la barre latérale'}).click()
 await expect(page.locator('.tool-layout')).not.toHaveClass(/sidebar-collapsed/)
})
test('export PDF avec une synthèse imprimable',async({page})=>{
 await page.goto('/')
 await selectPair(page)
 await page.evaluate(()=>{(window as typeof window & {printCalls:number}).printCalls=0;window.print=()=>{(window as typeof window & {printCalls:number}).printCalls++}})
 await page.locator('.file-menu summary').click()
 await page.getByRole('button',{name:'Exporter en PDF',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>(window as typeof window & {printCalls:number}).printCalls)).toBe(1)
 await page.emulateMedia({media:'print'})
 await expect(page.locator('.tool-layout')).toBeHidden()
 await expect(page.locator('.print-report')).toBeVisible()
 await expect(page.locator('.report-system')).toHaveCount(2)
 const pdf=await page.pdf({format:'A4',printBackground:true})
 expect(pdf.subarray(0,5).toString()).toBe('%PDF-')
 expect(pdf.length).toBeGreaterThan(10000)
})

test('ajout, limite et retrait de la comparaison avec compteur persistant',async({page})=>{
 await page.goto('/')
 await selectPair(page)
 await expect(page.locator('.comparison-count')).toHaveText('2')
 await page.getByRole('button',{name:'Ajouter Pilule à la comparaison',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('déjà deux familles')
 await expect(page.locator('.comparison-count')).toHaveText('2')
 await page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await openView(page,'Comparer')
 await expect(page.locator('.system-panel')).toHaveCount(1)
 await expect(page.getByLabel('Famille du système A')).toHaveValue('square')
 await page.reload()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await openView(page,'Comparer')
 await page.getByRole('button',{name:'Retirer Carré de la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveCount(0)
 await expect(page.getByText('Choisissez deux familles',{exact:true})).toBeVisible()
})

test('sélection visible, popup accessible et aperçu de réservation',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Familles')
 const add=page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true})
 await expect(add).toHaveCSS('background-color','rgb(255, 255, 255)')
 await add.click()
 const selected=page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true})
 await expect(selected).toHaveAttribute('aria-pressed','true')
 await page.mouse.move(0,0)
 await expect(selected).toHaveCSS('background-color','rgb(24, 24, 27)')
 await page.getByRole('button',{name:'Pourquoi cette forme : Arrondi léger ?'}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.getByText('Points d’attention',{exact:true})).toBeVisible()
 const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(accessibility.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
 await dialog.getByRole('button',{name:'Fermer',exact:true}).click()
 await openView(page,'Comparer')
 await expect(page.getByRole('heading',{name:'Réserver un atelier',exact:true})).toBeVisible()
 const remove=page.getByRole('button',{name:'Retirer Arrondi léger de la comparaison',exact:true})
 await remove.hover()
 // Wait for the button's colour transition to settle before inspecting the hover.
 await expect(remove).toHaveCSS('color','rgb(185, 28, 28)')
 const background=await remove.evaluate(button=>getComputedStyle(button).backgroundColor)
 expect(background).toMatch(/0\.05|5%/)
 await page.getByLabel('Votre adresse e-mail',{exact:true}).fill('test@example.com')
 await page.getByRole('button',{name:'Réserver ma place dans le système A',exact:true}).click()
 await expect(page.getByText('Exemple uniquement : aucune réservation n’est envoyée.')).toBeVisible()
 await page.setViewportSize({width:375,height:800})
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Pourquoi cette forme : Arrondi léger ?'}).click()
 const bounds=await page.getByRole('dialog').boundingBox()
 expect(bounds!.x).toBeGreaterThanOrEqual(0)
 expect(bounds!.width).toBeLessThanOrEqual(375)
 expect(bounds!.height).toBeLessThanOrEqual(800)
 await expect(page.getByRole('dialog').getByRole('button',{name:'Fermer',exact:true})).toBeInViewport()
})


test('recommandation sur place et catalogue indépendant du contexte',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await page.getByRole('button',{name:'Recommander une forme'}).click()
 await expect(page.locator('.recommendation-result h3')).toHaveText('Arrondi léger')
 await page.getByRole('button',{name:'Ajouter Arrondi léger à la comparaison',exact:true}).click()
 await expect(page.locator('.comparison-count')).toHaveText('1')
 await page.getByRole('button',{name:'Voir la comparaison',exact:true}).click()
 await expect(page.locator('.system-panel')).toHaveCount(1)
 await openView(page,'Familles')
 const names=await page.locator('.all-families h3').allTextContents()
 await expect(page.locator('.all-families .match-reason,.all-families .recommendation-badge')).toHaveCount(0)
 await openView(page,'Recommander')
 await page.getByLabel('Secteur',{exact:true}).selectOption('finance')
 await page.getByRole('radio',{name:'Rigoureux'}).click()
 await page.getByLabel('Public',{exact:true}).selectOption('expert')
 await expect(page.locator('.recommendation-result h3')).toHaveText('Carré')
 const a11y=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(a11y.violations.map(v=>v.id)).toEqual([])
 await openView(page,'Familles')
 expect(await page.locator('.all-families h3').allTextContents()).toEqual(names)
 await page.setViewportSize({width:375,height:900})
 await openView(page,'Recommander')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await expect(page.locator('.recommendation-result h3')).toHaveText('Carré')
})


test('création du bouton, mesures réelles, contrôles et sauvegarde',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Vérifier')
 const preview=page.locator('.draft-button')
 const check=(title:string)=>page.locator('.workshop-checks .audit-row').filter({hasText:title})
 await expect(check('Cible renforcée').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 const before=await preview.boundingBox()
 await page.getByRole('slider',{name:'Padding horizontal'}).fill('40')
 await expect.poll(async()=> (await preview.boundingBox())!.width).toBeGreaterThan(before!.width+35)
 await page.getByRole('slider',{name:'Padding vertical'}).fill('0')
 await expect(check('Cible minimale').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('slider',{name:'Padding vertical'}).fill('16')
 await expect(check('Cible renforcée').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 await page.getByLabel('Fond du bouton',{exact:true}).fill('#777777')
 await expect(check('Contraste du texte').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('slider',{name:'Taille du texte'}).fill('24')
 await expect(check('Contraste du texte').getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 await page.getByLabel('Texte du bouton').fill('Réserver ma place')
 const rect=await preview.boundingBox()
 await expect(page.locator('.workshop-dimensions')).toHaveText(`${rect!.width.toFixed(1)} × ${rect!.height.toFixed(1)} px`)
 await preview.focus()
 await page.keyboard.press('Enter')
 await expect(page.locator('.workshop-interaction')).toHaveCount(0)
 await expect(preview).toBeFocused()
 await page.reload()
 await openView(page,'Vérifier')
 await expect(page.getByLabel('Texte du bouton')).toHaveValue('Réserver ma place')
 await expect(page.getByRole('slider',{name:'Padding horizontal'})).toHaveValue('40')
 await page.getByLabel('Texte du bouton').fill('')
 await expect(check('Présence du libellé').getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Réinitialiser le bouton'}).click()
 await expect(page.getByLabel('Texte du bouton')).toHaveValue('Continuer')
 await page.setViewportSize({width:375,height:900})
 await page.getByLabel('Texte du bouton').fill('Un libellé volontairement très long pour vérifier le retour à la ligne sur un petit écran')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 const resized=await preview.boundingBox()
 await expect(page.locator('.workshop-dimensions')).toHaveText(`${resized!.width.toFixed(1)} × ${resized!.height.toFixed(1)} px`)
})


test('sliders compacts, valeurs manuelles et liens au survol',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Vérifier')
 await expect(page.locator('.workshop-parameters .parameter-slider')).toHaveCount(6)
 const value=page.getByRole('textbox',{name:'Valeur : Padding horizontal',exact:true})
 await value.click()
 await value.fill('32')
 await value.press('Enter')
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await expect(page.locator('.draft-button')).toHaveCSS('padding-left','32px')
 await value.click()
 await value.fill('50')
 await value.press('Escape')
 await expect(value).toHaveValue('32')
 const size=page.getByRole('textbox',{name:'Valeur : Taille du texte',exact:true})
 await size.fill('999')
 await size.press('Enter')
 await expect(size).toHaveValue('48')
 await size.fill('')
 await size.press('Tab')
 await expect(size).toHaveValue('48')
 await openView(page,'Familles')
 const explanation=page.getByRole('button',{name:'Pourquoi cette forme : Carré ?'})
 await explanation.hover()
 await expect(explanation).toHaveCSS('color','rgb(0, 0, 0)')
 await expect(explanation).toHaveCSS('text-decoration-line','underline')
 await explanation.click()
 const reference=page.getByRole('dialog').locator('.source-links a').first()
 await reference.hover()
 await expect(reference).toHaveCSS('color','rgb(0, 0, 0)')
})


test('usage de recommandation, bibliothèque de styles et ressources Orange',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await page.getByLabel('Secteur',{exact:true}).selectOption('culture')
 await page.getByLabel('Public',{exact:true}).selectOption('jeune')
 await page.getByRole('radio',{name:'Expressif'}).click()
 await page.getByLabel('Usage prévu').selectOption('identity')
 await page.getByRole('button',{name:'Recommander une forme'}).click()
 await expect(page.locator('.recommendation-result h3')).toHaveText('Triangle')
 await page.getByLabel('Usage prévu').selectOption('button')
 await expect(page.locator('.recommendation-result h3')).toHaveText('Pilule')
 await expect(page.locator('.recommendation-reasons')).toContainText('action avec du texte')
 await openView(page,'Vérifier')
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('32')
 await page.getByRole('button',{name:'Enregistrer le bouton dans les favoris',exact:true}).click()
 await page.getByLabel('Nom du bouton').fill('Action principale')
 await page.getByRole('dialog').getByRole('button',{name:'Enregistrer le bouton',exact:true}).click()
 await expect(page.getByLabel('Styles enregistrés')).toHaveCount(0)
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('5')
 await openView(page,'Favoris')
 await page.getByRole('button',{name:'Modifier le bouton Action principale',exact:true}).click()
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await page.reload()
 await openView(page,'Vérifier')
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('4')
 await openView(page,'Favoris')
 await page.getByRole('button',{name:'Modifier le bouton Action principale',exact:true}).click()
 await expect(page.locator('.draft-button')).toHaveCSS('padding-left','32px')
 await page.locator('.file-menu summary').click()
 const download=page.waitForEvent('download')
 await page.getByRole('button',{name:'Exporter',exact:true}).click()
 const file=await download
 const path=await file.path()
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('3')
 await page.getByLabel('Importer une exploration JSON').setInputFiles(path!)
 await expect(page.getByRole('slider',{name:'Padding horizontal',exact:true})).toHaveValue('32')
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Pourquoi cette forme : Carré ?'}).click()
 await expect(page.getByRole('dialog').getByText('Émotions et associations',{exact:true})).toBeVisible()
 await expect(page.getByRole('dialog').locator('.shape-associations')).toContainText('Rigueur')
 await page.keyboard.press('Escape')
 await openView(page,'Références')
 const orange=page.locator('.source-card').filter({hasText:'Orange · Recommandations'})
 await expect(orange.getByRole('img',{name:'Orange',exact:true})).toBeVisible()
 await expect(orange.getByRole('link',{name:'Consulter'})).toHaveAttribute('href','https://a11y-guidelines.orange.com/fr/')
})

test('états du bouton, contrastes et export du code',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write'])
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await page.getByLabel('Afficher l’état sélectionné').check()
 await page.getByRole('button',{name:'Survol',exact:true}).click()
 await page.locator('#button-background').fill('#ffffff')
 await expect(page.locator('.draft-button')).toHaveCSS('background-color','rgb(255, 255, 255)')
 await expect(page.locator('.workshop-checks .audit-row').filter({hasText:'Contraste du texte'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.locator('#button-foreground').fill('#000000')
 await expect(page.locator('.workshop-checks .audit-row').filter({hasText:'Contraste du texte'}).getByRole('img',{name:'Contrôle vérifié',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Focus',exact:true}).click()
 await page.locator('#button-focus-ring').fill('#ffffff')
 await expect(page.locator('.workshop-checks .audit-row').filter({hasText:'Contraste du contour de focus'}).getByRole('img',{name:'À ajuster',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Désactivé',exact:true}).click()
 await expect(page.locator('.draft-button')).toBeDisabled()
 await expect(page.locator('.workshop-checks')).toContainText('exemptés des exigences de contraste')
 await page.getByRole('button',{name:'Repos',exact:true}).click()
 await page.getByLabel('Texte du bouton').fill('<b>Continuer</b>')
 await page.getByRole('button',{name:'Exporter le code',exact:true}).click()
 const code=page.getByRole('textbox',{name:'Code HTML et CSS'})
 await expect(code).toContainText('&lt;b&gt;Continuer&lt;/b&gt;')
 await page.getByRole('button',{name:'Copier le code',exact:true}).click()
 await expect(page.getByRole('dialog').getByRole('status')).toHaveText('Code copié.')
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain(':hover:not(:disabled) { color: #000000; background: #ffffff;')
 await page.keyboard.press('Escape')
 await page.reload()
 await openView(page,'Créer un bouton')
 await page.getByRole('button',{name:'Survol',exact:true}).click()
 await expect(page.locator('#button-background')).toHaveValue('#ffffff')
})

test('historique des réglages et raccourcis clavier',async({page})=>{
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await expect(page.getByRole('button',{name:'Annuler',exact:true})).toBeDisabled()
 const padding=page.getByRole('textbox',{name:'Valeur : Padding horizontal',exact:true})
 await padding.click()
 await padding.fill('30')
 await padding.fill('40')
 await padding.press('Enter')
 await page.getByRole('button',{name:'Annuler',exact:true}).click()
 await expect(padding).toHaveValue('20')
 await page.getByRole('button',{name:'Rétablir',exact:true}).click()
 await expect(padding).toHaveValue('40')
 await page.getByRole('button',{name:'Réinitialiser le bouton'}).click()
 await expect(padding).toHaveValue('20')
 await page.keyboard.press('ControlOrMeta+z')
 await expect(padding).toHaveValue('40')
 await page.keyboard.press('ControlOrMeta+Shift+z')
 await expect(padding).toHaveValue('20')
 await page.getByLabel('Texte du bouton').fill('Réserver')
 await page.getByRole('tab',{name:'Favoris',exact:true}).click()
 await openView(page,'Créer un bouton')
 await page.getByRole('button',{name:'Annuler',exact:true}).click()
 await expect(page.getByLabel('Texte du bouton')).toHaveValue('Continuer')
})

test('gestion des favoris, mise à jour et annulation de suppression',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await page.getByRole('button',{name:'Enregistrer le bouton dans les favoris'}).click()
 await page.getByLabel('Nom du bouton').fill('Principal')
 await page.getByRole('button',{name:'Enregistrer le bouton',exact:true}).click()
 await page.getByLabel('Texte du bouton').fill('Réserver')
 await page.getByRole('button',{name:'Enregistrer le bouton dans les favoris'}).click()
 await page.getByRole('button',{name:'Mettre à jour le bouton',exact:true}).click()
 await openView(page,'Favoris')
 await expect(page.locator('.saved-button-card')).toHaveCount(1)
 await expect(page.locator('.saved-button-sample')).toHaveText('Réserver')
 await page.getByRole('button',{name:'Dupliquer le bouton Principal',exact:true}).click()
 await expect(page.locator('.saved-button-card')).toHaveCount(2)
 await page.getByRole('button',{name:'Renommer le bouton Principal (copie)',exact:true}).click()
 await page.getByLabel('Nom du bouton').fill('Secondaire')
 await page.getByRole('dialog').getByRole('button',{name:'Renommer',exact:true}).click()
 await page.getByRole('button',{name:'Supprimer le bouton Principal',exact:true}).click()
 await expect(page.locator('.saved-button-card')).toHaveCount(1)
 await page.locator('.notification').getByRole('button',{name:'Annuler',exact:true}).click()
 await expect(page.locator('.saved-button-card h3')).toHaveText(['Principal','Secondaire'])
 await page.getByRole('button',{name:'Modifier le bouton Secondaire',exact:true}).click()
 await page.getByRole('button',{name:'Enregistrer le bouton dans les favoris'}).click()
 await page.getByLabel('Enregistrer une copie').check()
 await page.getByLabel('Nom du bouton').fill('Troisième')
 await page.getByRole('button',{name:'Enregistrer le bouton',exact:true}).click()
 await page.reload()
 await openView(page,'Favoris')
 await expect(page.locator('.saved-button-card')).toHaveCount(3)
 const cards=await page.locator('.saved-button-card').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().top))
 expect(new Set(cards).size).toBe(1)
 const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(result.violations.map(v=>v.id)).toEqual([])
})

test('aperçus selon l’usage et atelier stable sur desktop',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await page.getByRole('button',{name:'Recommander une forme'}).click()
 for(const [usage,selector] of [['button','.recommendation-sample-action'],['card','.recommendation-sample-card'],['badge','.recommendation-sample-badge'],['identity','.recommendation-preview svg']]){
  await page.getByLabel('Usage prévu').selectOption(usage)
  await expect(page.locator(selector)).toBeVisible()
 }
 await openView(page,'Créer un bouton')
 const preview=page.locator('.workshop-preview')
 await page.evaluate(()=>window.scrollTo(0,200))
 await expect(preview).toBeInViewport()
 const before=(await preview.boundingBox())!.y
 await page.locator('.workshop-checks').evaluate(element=>element.scrollTop=element.scrollHeight)
 expect((await preview.boundingBox())!.y).toBeCloseTo(before,1)
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.locator('.draft-button')).toHaveCSS('transition-duration','0s')
 await page.setViewportSize({width:375,height:900})
 await expect(page.getByLabel('Texte du bouton')).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('survol réel après réglage d’un état, repères de défilement et historique dans le titre',async({page})=>{
 await page.setViewportSize({width:1440,height:850})
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 const preview=page.locator('.draft-button')
 const toolbar=page.getByRole('group',{name:'Historique du bouton'})
 await expect(toolbar).toHaveCSS('background-color','rgb(255, 255, 255)')
 await expect(toolbar.getByRole('button',{name:'Annuler',exact:true})).toBeDisabled()
 await expect(page.locator('.workshop-settings').getByRole('button',{name:'Annuler',exact:true})).toHaveCount(0)
 const rest=await preview.evaluate(element=>getComputedStyle(element).backgroundColor)
 await preview.hover()
 await expect(preview).not.toHaveCSS('background-color',rest)
 await page.getByRole('button',{name:'Survol',exact:true}).click()
 await page.locator('#button-background').fill('#006600')
 await page.locator('.workshop-section-head').first().hover()
 await expect(preview).toHaveCSS('background-color',rest)
 await preview.hover()
 await expect(preview).toHaveCSS('background-color','rgb(0, 102, 0)')
 await expect(page.locator('.preview-state')).toHaveText('Survol')
 await expect(toolbar.getByRole('button',{name:'Annuler',exact:true})).toBeEnabled()
 for(const selector of ['.workshop-settings','.workshop-checks']) {
  const panel=page.locator(selector)
  await panel.evaluate(element=>element.scrollTop=0)
  const hint=panel.locator('.scroll-hint')
  await expect(hint).toBeVisible()
  await expect(hint).toContainText('Faites défiler')
  const box=await hint.boundingBox(),parent=await panel.boundingBox()
  expect(box!.y+box!.height).toBeLessThanOrEqual(parent!.y+parent!.height+1)
  await panel.evaluate(element=>element.scrollTop=element.scrollHeight)
  await expect(hint).toBeHidden()
  const bottomSpace=await panel.evaluate(element=>{const last=element.querySelector('.scroll-hint')?.previousElementSibling;return last ? element.getBoundingClientRect().bottom-last.getBoundingClientRect().bottom : 0})
  expect(bottomSpace).toBeLessThanOrEqual(24)
 }
 await page.setViewportSize({width:375,height:900})
 await openView(page,'Créer un bouton')
 await expect(page.locator('.scroll-hint[data-overflow="true"]')).toHaveCount(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('score de qualité global, détail et pistes de correction',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 const score=page.locator('.button-quality-trigger')
 await expect(score).toHaveAccessibleName('Score de qualité du bouton : 90 sur 100')
 await page.getByRole('slider',{name:'Taille du texte',exact:true}).fill('16')
 await expect(score).toHaveAccessibleName('Score de qualité du bouton : 100 sur 100')
 await page.getByRole('button',{name:'Survol',exact:true}).click()
 await page.locator('#button-foreground').fill('#ffffff')
 await page.locator('#button-background').fill('#ffffff')
 await expect(score).toHaveAccessibleName('Score de qualité du bouton : 59 sur 100')
 await page.getByRole('button',{name:'Repos',exact:true}).click()
 await expect(score).toHaveAccessibleName('Score de qualité du bouton : 59 sur 100')
 await score.click()
 const dialog=page.getByRole('dialog')
 await expect(dialog).toHaveAccessibleName('Score de qualité du bouton')
 await expect(dialog.locator('.quality-criterion')).toHaveCount(7)
 await expect(dialog.locator('.quality-priorities')).toContainText('survol')
 await expect(dialog.locator('.quality-total')).toContainText('ni la conversion')
 const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(result.violations.map(v=>v.id)).toEqual([])
 await page.keyboard.press('Escape')
 await page.getByLabel('Texte du bouton').fill('')
 await expect(score).toHaveAccessibleName('Score de qualité du bouton : 20 sur 100')
 await page.setViewportSize({width:375,height:900})
 await openView(page,'Créer un bouton')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('texte minuscule pénalisé et explication des plafonds',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await page.getByRole('slider',{name:'Padding horizontal',exact:true}).fill('60')
 await page.getByRole('slider',{name:'Padding vertical',exact:true}).fill('40')
 await page.getByRole('slider',{name:'Taille du texte',exact:true}).fill('8')
 await expect(page.locator('.button-quality-trigger')).toHaveAccessibleName('Score de qualité du bouton : 25 sur 100')
 await page.locator('.button-quality-trigger').click()
 await expect(page.getByRole('dialog').locator('.quality-limits')).toContainText('Texte à 8 px')
 await expect(page.getByRole('dialog').locator('.quality-priorities')).toContainText('taille du texte')
 await page.keyboard.press('Escape')
 await page.getByRole('slider',{name:'Taille du texte',exact:true}).fill('16')
 await expect(page.locator('.button-quality-trigger')).toHaveAccessibleName('Score de qualité du bouton : 100 sur 100')
})

test('roue des évocations accessible et liens externes soulignés',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Familles')
 for(const name of ['Carré','Arrondi léger','Pilule','Cercle','Triangle','Organique']){
  await page.getByRole('button',{name:`Pourquoi cette forme : ${name} ?`}).click()
  const dialog=page.getByRole('dialog')
  const wheel=dialog.getByRole('group',{name:'Carte des évocations'})
  await expect(wheel.getByRole('button')).toHaveCount(3)
  const last=wheel.getByRole('button').last()
  await last.focus()
  await page.keyboard.press('Enter')
  await expect(last).toHaveAttribute('aria-pressed','true')
  await expect(dialog.locator('.evocation-detail>strong')).toHaveText(await last.innerText())
  await expect(dialog.locator('.evocation-detail')).toContainText('Exemple')
  for(const link of await dialog.locator('a[href^="https://"]').all())await expect(link).toHaveCSS('text-decoration-line','underline')
  if(name==='Carré'){
   const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
   expect(result.violations.map(v=>v.id)).toEqual([])
  }
  await page.keyboard.press('Escape')
 }
 await openView(page,'Référentiels')
 const external=page.locator('main a[href^="https://"]')
 await expect(external).toHaveCount(6)
 for(const link of await external.all())await expect(link).toHaveCSS('text-decoration-line','none')
 await page.setViewportSize({width:375,height:900})
 await openView(page,'Familles')
 await page.getByRole('button',{name:'Pourquoi cette forme : Organique ?'}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const overflow=await page.getByRole('dialog').evaluate(element=>element.scrollWidth>element.clientWidth)
 expect(overflow).toBe(false)
})

test('réglages compacts, couleurs hexadécimales et popup de couleur',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await expect(page.locator('.workshop-settings .bits-control')).toHaveCount(6)
 const hex=page.locator('#button-background')
 await hex.fill('8b5cf6')
 await hex.press('Enter')
 await expect(hex).toHaveValue('#8b5cf6')
 await expect(page.locator('.draft-button')).toHaveCSS('background-color','rgb(139, 92, 246)')
 await hex.fill('#abc')
 await hex.press('Enter')
 await expect(hex).toHaveValue('#aabbcc')
 await hex.fill('#123456')
 await hex.press('Escape')
 await expect(hex).toHaveValue('#aabbcc')
 await hex.fill('#zzzzzz')
 await hex.press('Enter')
 await expect(hex).toHaveValue('#aabbcc')
 await expect(page.getByRole('alert')).toContainText('Couleur invalide')
 const trigger=page.getByRole('button',{name:'Choisir la couleur : Fond du bouton',exact:true})
 await trigger.click()
 const picker=page.getByRole('dialog',{name:'Couleur : Fond du bouton',exact:true})
 await expect(picker).toBeVisible()
 await expect(picker.getByRole('group',{name:'Couleurs prédéfinies'}).getByRole('button')).toHaveCount(14)
 await picker.getByRole('button',{name:'Bleu',exact:true}).click()
 await expect(hex).toHaveValue('#3b82f6')
 const plane=picker.locator('.color-plane')
 const bounds=await plane.boundingBox()
 await page.mouse.move(bounds!.x+bounds!.width*.5,bounds!.y+bounds!.height*.3)
 await page.mouse.down()
 await page.mouse.move(bounds!.x+bounds!.width*.8,bounds!.y+bounds!.height*.5,{steps:8})
 await page.mouse.up()
 const picked=await hex.inputValue()
 expect(picked).not.toBe('#3b82f6')
 await picker.getByRole('slider',{name:'Teinte : Fond du bouton',exact:true}).fill('180')
 expect(await hex.inputValue()).not.toBe(picked)
 await picker.locator('.color-precise summary').click()
 await picker.getByRole('slider',{name:'Saturation : Fond du bouton',exact:true}).fill('0')
 await picker.getByRole('slider',{name:'Luminosité : Fond du bouton',exact:true}).fill('100')
 await expect(hex).toHaveValue('#ffffff')
 await picker.getByRole('slider',{name:'Teinte : Fond du bouton',exact:true}).fill('270')
 await picker.getByRole('slider',{name:'Saturation : Fond du bouton',exact:true}).fill('100')
 await expect(hex).toHaveValue('#8000ff')
 const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
 await page.keyboard.press('Escape')
 await expect(picker).toBeHidden()
 await expect(trigger).toBeFocused()
 await page.getByRole('button',{name:'Annuler',exact:true}).click()
 await expect(hex).toHaveValue('#ffffff')
 await page.reload()
 await openView(page,'Créer un bouton')
 await expect(hex).toHaveValue('#ffffff')
})

test('sélecteur de couleur sur petit écran et changement d’état',async({page})=>{
 await page.setViewportSize({width:375,height:900})
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await openView(page,'Créer un bouton')
 await page.getByRole('button',{name:'Survol',exact:true}).click()
 await page.getByRole('button',{name:'Choisir la couleur : Fond du bouton',exact:true}).click()
 const picker=page.getByRole('dialog',{name:'Couleur : Fond du bouton',exact:true})
 await expect(picker).toBeVisible()
 const rect=await picker.boundingBox()
 expect(rect!.x).toBeGreaterThanOrEqual(0)
 expect(rect!.x+rect!.width).toBeLessThanOrEqual(375)
 await picker.getByRole('button',{name:'Rouge',exact:true}).click()
 await page.keyboard.press('Escape')
 await expect(page.locator('#button-background')).toHaveValue('#ef4444')
 await page.getByRole('button',{name:'Repos',exact:true}).click()
 await expect(page.locator('#button-background')).toHaveValue('#18181b')
 await page.getByRole('button',{name:'Focus',exact:true}).click()
 await expect(page.getByLabel('Focus',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
